version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./apple-app-site-association /usr/share/nginx/html/
    ports:
      - 443:443
      - 80:80
